"""
Gmail SMTP Client

Sends email replies via Gmail SMTP server.
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
import logging

logger = logging.getLogger(__name__)


class GmailClient:
    """Client for sending emails via Gmail SMTP"""
    
    def __init__(
        self,
        smtp_server: str,
        smtp_port: int,
        email_address: str,
        email_password: str
    ):
        """
        Initialize Gmail SMTP client.
        
        Args:
            smtp_server: SMTP server address (smtp.gmail.com)
            smtp_port: SMTP port (465 for SSL)
            email_address: Gmail address
            email_password: Gmail app-specific password
        """
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.email_address = email_address
        self.email_password = email_password
    
    def send_reply(
        self,
        to: str,
        subject: str,
        body: str,
        in_reply_to: Optional[str] = None,
        references: Optional[str] = None
    ) -> str:
        """
        Send an email reply.
        
        Args:
            to: Recipient email address
            subject: Email subject (will be prefixed with "Re: " if not already)
            body: Email body text
            in_reply_to: Original email's Message-ID for threading
            references: Chain of Message-IDs for threading
            
        Returns:
            Message-ID of sent email
            
        Raises:
            Exception: If sending fails
        """
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.email_address
            msg['To'] = to
            
            # Add "Re: " prefix if not already present
            if not subject.lower().startswith('re:'):
                msg['Subject'] = f"Re: {subject}"
            else:
                msg['Subject'] = subject
            
            # Add threading headers for proper email threading
            if in_reply_to:
                msg['In-Reply-To'] = in_reply_to
            
            if references:
                # Append current in_reply_to to references chain
                if in_reply_to and in_reply_to not in references:
                    msg['References'] = f"{references} {in_reply_to}"
                else:
                    msg['References'] = references
            elif in_reply_to:
                msg['References'] = in_reply_to
            
            # Attach body
            msg.attach(MIMEText(body, 'plain'))
            
            # Send via SMTP
            logger.info(f"Sending email to {to} via Gmail SMTP")
            with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port) as server:
                server.login(self.email_address, self.email_password)
                server.send_message(msg)
            
            # Get Message-ID (generated by server)
            message_id = msg.get('Message-ID', '')
            logger.info(f"Email sent successfully to {to}, Message-ID: {message_id}")
            
            return message_id
            
        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"SMTP authentication failed: {e}")
            raise Exception(f"Gmail authentication failed: {e}")
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {e}")
            raise Exception(f"Failed to send email: {e}")
        except Exception as e:
            logger.error(f"Unexpected error sending email: {e}")
            raise Exception(f"Failed to send email: {e}")
    
    def test_connection(self) -> bool:
        """
        Test SMTP connection and authentication.
        
        Returns:
            True if connection successful, False otherwise
        """
        try:
            with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port) as server:
                server.login(self.email_address, self.email_password)
            logger.info("Gmail SMTP connection test successful")
            return True
        except Exception as e:
            logger.error(f"Gmail SMTP connection test failed: {e}")
            return False


def get_gmail_client() -> GmailClient:
    """
    Get Gmail client instance from environment variables.
    
    Returns:
        GmailClient instance
    """
    smtp_server = os.getenv('GMAIL_SMTP_SERVER', 'smtp.gmail.com')
    smtp_port = int(os.getenv('GMAIL_SMTP_PORT', '465'))
    email_address = os.getenv('EMAIL_ADDRESS', '')
    email_password = os.getenv('EMAIL_PASSWORD', '')
    
    if not email_address or not email_password:
        raise ValueError("EMAIL_ADDRESS and EMAIL_PASSWORD must be set in environment")
    
    return GmailClient(smtp_server, smtp_port, email_address, email_password)
